pip install pyautogui
pip install mouse
pip install keyboard
pip install psutil
pip install opencv-python
pip install imutils
pip install numpy
pip install pyperclip
pip install openpyxl
pip install datetime
pip install pillow
